## CV交叉验证

In [7]:
import numpy as np
from sklearn.model_selection import KFold,StratifiedKFold

### cross_val_score
用这个评价cv得分

### kfold
划分k份，用k-1份训练，1份验证

In [2]:
X = list('abcdefghijk')
kf = KFold(n_splits=3)
for train, test in kf.split(X):
    print(train, test)

[ 4  5  6  7  8  9 10] [0 1 2 3]
[ 0  1  2  3  8  9 10] [4 5 6 7]
[0 1 2 3 4 5 6 7] [ 8  9 10]


### 分层KFOLD
每份kfold保持总体样本比例

In [8]:
X, y = np.ones((20, 1)), np.hstack(([0] * 15, [1] * 5))

In [14]:
skf = StratifiedKFold(n_splits=3)
for i, (train_idx, test_idx) in enumerate(skf.split(X, y)):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    print(i,  X_train, X_test, y_train, y_test)

0 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] [0 0 0 0 0 0 0 0 0 0 1 1 1] [0 0 0 0 0 1 1]
1 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] [0 0 0 0 0 0 0 0 0 0 1 1 1] [0 0 0 0 0 1 1]
2 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] [0 0 0 0 0 0 0 0 0 0 1 1 1 1] [0 0 0 0 0 1]
